import { ReactComponent as Heart } from "./heart.svg";
import { ReactComponent as Hide } from "./hide.svg";
import { ReactComponent as Next } from "./next.svg";
import { ReactComponent as Pause } from "./pause.svg";
import { ReactComponent as Play } from "./play.svg";
import { ReactComponent as Preview } from "./preview.svg";
import { ReactComponent as Search } from "./search.svg";
import { ReactComponent as Share } from "./share.svg";
import { ReactComponent as Shuffle } from "./shuffle.svg";
import { ReactComponent as Repeat } from "./repeat.svg";
import { ReactComponent as User } from "./user.svg";
import { ReactComponent as Library } from "./library.svg";
import { ReactComponent as Thumbnail } from "./default-thumbnail.svg";
import { ReactComponent as Queue } from "./playlist.svg";
import { ReactComponent as Download } from "./download.svg";
import { ReactComponent as Add } from "./addPlaylist.svg";
import { ReactComponent as Clear } from "./clear.svg";
import { ReactComponent as Spotify } from "./spotify-logo.svg";
import { ReactComponent as Yt } from "./youtube-logo.svg";
import { ReactComponent as Remove } from "./remove.svg";
import { ReactComponent as Volume } from "./volume.svg";

export { Volume };
export { Heart };
export { Remove };
export { Spotify };
export { Yt };
export { Clear };
export { Add };
export { Library };
export { User };
export { Thumbnail };
export { Download };
export { Search };
export { Shuffle };
export { Preview };
export { Pause };
export { Next };
export { Hide };
export { Repeat };
export { Play };
export { Share };
export { Queue };
